[project]
name = "logos-blockchain-explorer"
version = "0.1.0"
requires-python = ">=3.14,<3.15"
dependencies = [
    "httpx>=0.28.1",
    "pydantic>=2.12",
    "starlette>=0.49",
    "uvicorn~=0.38.0",
]

[dependency-groups]
dev = [
    "pytest>=9.0.2",
]

[tool.pytest.ini_options]
pythonpath = ["src"]

[tool.pyright]
include = ["src"]
